### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by taleena** [samlanning/tree-sitter-ql#13]
Hi, can you add an explicit license to this repo (such as MIT, which would be consistent with the rest of tree-sitter)? Thanks!

**Comment by panekj** [comment]
@tausbn could we have some action done regarding this issue or at least some kind of response?

**Comment by tausbn** [comment]
Thanks for the prod. I was honestly not aware of this issue. 😞

I have added a `LICENSE` file, licensing the code under the MIT license.
